import React from 'react';
import { GeneratedImage } from '../types';
import { DownloadIcon } from './icons/DownloadIcon';
import { ShareIcon } from './icons/ShareIcon';
import { MagicWandIcon } from './icons/MagicWandIcon';
import { Spinner } from './Spinner';

interface ResultsDisplayProps {
  images: GeneratedImage[];
  isLoading: boolean;
  onImageClick: (image: GeneratedImage) => void;
  onRemoveBackground: (image: GeneratedImage) => void;
}

interface ImageCardProps {
    image: GeneratedImage;
    onImageClick: (image: GeneratedImage) => void;
    onRemoveBackground: (image: GeneratedImage) => void;
}

const ImageCard: React.FC<ImageCardProps> = ({ image, onImageClick, onRemoveBackground }) => {
  const canShare = typeof navigator !== 'undefined' && !!navigator.share;
  
  const handleDownload = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (image.status !== 'success') return;
    const link = document.createElement('a');
    link.href = image.imageUrl;
    const sanitizedPrompt = image.prompt.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    link.download = `variation_${sanitizedPrompt.slice(0, 20)}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!canShare) {
        alert('Web Share API is not available on your browser.');
        return;
    }
    try {
        const response = await fetch(image.imageUrl);
        const blob = await response.blob();
        const file = new File([blob], 'robo-ai-image.png', { type: blob.type });

        if (navigator.canShare && navigator.canShare({ files: [file] })) {
            await navigator.share({
                files: [file],
                title: 'Image generated by Robo AI',
                text: `Check out this image I created for the prompt: "${image.prompt}"`,
            });
        } else {
            alert("Your browser doesn't support sharing files.");
        }
    } catch (error) {
        console.error('Error sharing image:', error);
        alert('Could not share the image.');
    }
  };

  const handleRemoveBackground = (e: React.MouseEvent) => {
    e.stopPropagation();
    onRemoveBackground(image);
  };


  return (
    <div 
      className="relative group bg-gray-100 dark:bg-gray-800 rounded-lg overflow-hidden shadow-lg transition-all transform hover:-translate-y-1"
      onClick={() => image.status === 'success' && onImageClick(image)}
    >
      <div className={`aspect-w-1 aspect-h-1 w-full ${image.status === 'success' ? 'cursor-pointer' : 'cursor-default'}`}>
        {image.status === 'pending' && (
          <div className="absolute inset-0 flex items-center justify-center bg-gray-200 dark:bg-gray-700">
            <Spinner />
          </div>
        )}
        {image.status === 'error' && (
          <div className="absolute inset-0 flex flex-col items-center justify-center bg-red-900 bg-opacity-50 p-4 text-center">
            <span className="text-5xl mb-2">😞</span>
            <p className="text-red-200 text-sm">Generation Failed</p>
          </div>
        )}
        {image.status === 'success' && (
            <img src={image.imageUrl} alt={image.prompt} className="w-full h-full object-cover" />
        )}
      </div>
      <div className="absolute bottom-0 left-0 right-0 bg-black bg-opacity-70 p-3 translate-y-full group-hover:translate-y-0 transition-transform pointer-events-none">
        <p className="text-white text-sm truncate">{image.prompt}</p>
      </div>
      {image.status === 'success' && (
        <div className="absolute top-2 right-2 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
          {canShare && (
            <button
              onClick={handleShare}
              className="bg-black bg-opacity-50 text-white p-2 rounded-full hover:bg-indigo-500 transition-all"
              aria-label="Share image"
            >
              <ShareIcon className="w-5 h-5" />
            </button>
          )}
          <button
            onClick={handleRemoveBackground}
            className="bg-black bg-opacity-50 text-white p-2 rounded-full hover:bg-indigo-500 transition-all"
            aria-label="Remove background"
          >
            <MagicWandIcon className="w-5 h-5" />
          </button>
          <button
            onClick={handleDownload}
            className="bg-black bg-opacity-50 text-white p-2 rounded-full hover:bg-indigo-500 transition-all"
            aria-label="Download image"
          >
            <DownloadIcon className="w-5 h-5" />
          </button>
        </div>
      )}
    </div>
  );
};


export const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ images, isLoading, onImageClick, onRemoveBackground }) => {
  const successfulImages = images.filter(img => img.status === 'success');

  const handleDownloadAll = async () => {
    if (successfulImages.length === 0 || !window.JSZip || !window.saveAs) {
      alert("No successful images to download, or required libraries are missing.");
      return;
    }

    const zip = new window.JSZip();
    
    await Promise.all(successfulImages.map(async (image) => {
      try {
        const response = await fetch(image.imageUrl);
        const blob = await response.blob();
        const filename = `${image.prompt.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30)}.png`;
        zip.file(filename, blob);
      } catch (error) {
        console.error(`Failed to fetch image for zipping: ${image.prompt}`, error);
      }
    }));

    zip.generateAsync({ type: 'blob' }).then((content: any) => {
      window.saveAs(content, 'robo-ai-edits.zip');
    });
  };

  return (
    <div className="bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-transparent p-6 rounded-2xl shadow-lg min-h-[500px]">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-2xl font-semibold text-gray-900 dark:text-white">Results</h2>
        {successfulImages.length > 0 && (
          <button
            onClick={handleDownloadAll}
            className="flex items-center gap-2 bg-indigo-600 text-white font-semibold py-2 px-4 rounded-lg hover:bg-indigo-500 transition-colors"
          >
            <DownloadIcon className="w-5 h-5" />
            <span>Download All</span>
          </button>
        )}
      </div>
      {images.length === 0 && !isLoading ? (
        <div className="flex flex-col items-center justify-center h-96 text-gray-400 dark:text-gray-500">
            <p className="text-lg">Your generated images will appear here.</p>
            <p className="text-sm">Configure your edits and click "Generate".</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-4">
          {images.map((image) => (
            <ImageCard key={image.id} image={image} onImageClick={onImageClick} onRemoveBackground={onRemoveBackground} />
          ))}
        </div>
      )}
    </div>
  );
};